// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prh-clean-modern/CleanModern.tsx": () => import("../components/mockups/prh-clean-modern/CleanModern.tsx"),
  "./components/mockups/prh-front-table/App.tsx": () => import("../components/mockups/prh-front-table/App.tsx"),
  "./components/mockups/prh-ink-ivory/InkIvory.tsx": () => import("../components/mockups/prh-ink-ivory/InkIvory.tsx"),
  "./components/mockups/prh-paperback-warm/PaperbackWarm.tsx": () => import("../components/mockups/prh-paperback-warm/PaperbackWarm.tsx")
};
